# Generated by Django 6.0.5 on 2026-08-19 12:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.profile_image_upload_path),
        ),
    ]
