# Generated by Django 6.0.5 on 2026-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
