# Generated by Django 6.0.5 on 2026-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_additional_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('inventory', 'Inventory'), ('procurement', 'Procurement'), ('engineer', 'Engineer'), ('finance', 'Finance'), ('manager', 'Manager'), ('management', 'Management'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
