# Generated by Django 6.0.5 on 2026-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
