# Generated by Django 6.0.5 on 2026-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('total_components', models.IntegerField(default=0)),
                ('total_stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_pr', models.IntegerField(default=0)),
                ('pending_po', models.IntegerField(default=0)),
                ('pending_approvals', models.IntegerField(default=0)),
                ('total_bom', models.IntegerField(default=0)),
            ],
        ),
    ]
