# Generated by Django 6.0.5 on 2026-08-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('materialrequest', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='components.component')),
            ],
            options={
                'ordering': ['received_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['component', 'issued'], name='inv_comp_issued_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_store_quantity', models.PositiveIntegerField(default=0)),
                ('procurement_shortage_quantity', models.PositiveIntegerField(default=0)),
                ('issued_store_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partially Issued'), ('ISSUED', 'Issued'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='materialrequest.materialrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['component', 'status'], name='inv_res_comp_stat_idx'), models.Index(fields=['material_request', 'status'], name='inv_res_mr_stat_idx')],
                'constraints': [models.UniqueConstraint(fields=('material_request', 'component'), name='uniq_inv_res_mr_comp')],
            },
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('requested_quantity', models.PositiveIntegerField(default=0)),
                ('store_quantity', models.PositiveIntegerField(default=0)),
                ('purchased_quantity', models.PositiveIntegerField(default=0)),
                ('qc_passed_quantity', models.PositiveIntegerField(default=0)),
                ('qc_failed_quantity', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('issued_store_quantity', models.PositiveIntegerField(default=0)),
                ('issued_purchased_quantity', models.PositiveIntegerField(default=0)),
                ('po_numbers', models.JSONField(blank=True, default=list)),
                ('inward_codes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Issued'), ('READY', 'Ready'), ('ISSUED', 'Issued'), ('COMPLETED', 'Completed - Legacy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_inventory_items', to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_inventory_items', to='materialrequest.materialrequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['material_request', 'status'], name='proj_inv_mr_stat_idx'), models.Index(fields=['component', 'status'], name='proj_inv_comp_stat_idx')],
                'constraints': [models.UniqueConstraint(fields=('material_request', 'component'), name='uniq_proj_inv_mr_comp')],
            },
        ),
    ]
