# Generated by Django 6.0.5 on 2026-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='issued_serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectinventory',
            name='issued_purchased_serials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectinventory',
            name='issued_store_serials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectinventory',
            name='purchased_serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
