# Generated by Django 6.0.5 on 2026-07-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='stockinitem',
            name='stock_in',
        ),
        migrations.RemoveField(
            model_name='stockinitem',
            name='component',
        ),
        migrations.RemoveField(
            model_name='stockoutitem',
            name='stock_out',
        ),
        migrations.RemoveField(
            model_name='stockoutitem',
            name='component',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moved', models.BooleanField(default=False)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='components.component')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryLedger',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='StockInItem',
        ),
        migrations.DeleteModel(
            name='StockOut',
        ),
        migrations.DeleteModel(
            name='StockOutItem',
        ),
    ]
