# Generated by Django 5.2.17 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_component_type'),
        ('inventory', '0002_inventory_issued_serial_numbers_and_more'),
        ('inward', '0003_inwardentry_qc_failed_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('source_details', models.JSONField(default=dict)),
                ('units', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.component')),
                ('source_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_allocations', to='inventory.inventory')),
                ('source_inward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_allocations', to='inward.inwardentry')),
            ],
        ),
        migrations.CreateModel(
            name='SerialPurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('unit_index', models.PositiveIntegerField()),
                ('allocated_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_costs', to='inventory.serialcostallocation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.component')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('component', 'serial_number'), name='unique_component_serial_cost'), models.UniqueConstraint(fields=('allocation', 'unit_index'), name='unique_cost_allocation_slot')],
            },
        ),
    ]
