# Generated by Django 6.0.5 on 2026-09-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_received_date_optional'),
        ('inventory', '0007_drone_instances'),
    ]

    operations = [
    ]
