# Generated by Django 6.0.5 on 2026-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INVENTORY', 'Inventory Report'), ('PROCUREMENT', 'Procurement Report'), ('FINANCE', 'Finance Report'), ('BOM', 'BOM Report')], max_length=20)),
                ('generated_by', models.CharField(max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
