# Generated by Django 6.0.5 on 2026-06-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0003_component_tally_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('issued_to', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('SCRAP', 'Scrap'), ('RETURN', 'Return'), ('ISSUE', 'Issue')], default='ISSUE', max_length=20)),
                ('issued_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutwardLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.component')),
                ('outward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='outward.outwardentry')),
            ],
        ),
    ]
