# Generated by Django 6.0.5 on 2026-06-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('outward_type', models.CharField(choices=[('SCRAP', 'Scrap'), ('SALES', 'Sales'), ('EVENT', 'Event')], default='SCRAP', max_length=20)),
                ('out_date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('gate_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_components', models.PositiveIntegerField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outward_entries', to='components.component')),
            ],
        ),
    ]
