# Generated by Django 6.0.5 on 2026-07-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardentry',
            name='drone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
