# Generated by Django 6.0.5 on 2026-06-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_tally_reference'),
        ('outward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outwardentry',
            old_name='department',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='outwardentry',
            old_name='issued_date',
            new_name='out_date',
        ),
        migrations.RemoveField(
            model_name='outwardentry',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='outwardentry',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outward_entries', to='components.component'),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='deliverables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='gate_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='no_of_components',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='outward_type',
            field=models.CharField(choices=[('SCRAP', 'Scrap'), ('SALES', 'Sales'), ('EVENT', 'Event')], default='SCRAP', max_length=20),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OutwardLineItem',
        ),
    ]
