# Generated by Django 6.0.5 on 2026-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('outward', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outwardentry',
            options={'ordering': ['-out_date', '-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='inventory_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='item_type',
            field=models.CharField(choices=[('COMPONENT', 'Component'), ('DRONE', 'Drone')], default='COMPONENT', max_length=20),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='returned_serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='outwardentry',
            index=models.Index(fields=['outward_type', 'item_type', 'status'], name='out_type_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='outwardentry',
            index=models.Index(fields=['component', 'outward_type'], name='out_comp_type_idx'),
        ),
    ]
