# Generated by Django 6.0.5 on 2026-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('outward', '0002_alter_outwardentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardentry',
            name='moved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='moved_to_inventory',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='requested_by',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='requested_by_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('ENGINEER', 'Engineer')], db_index=True, default='DIRECT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='outwardentry',
            index=models.Index(fields=['source', 'moved_to_inventory', 'approval_status'], name='out_source_move_appr_idx'),
        ),
    ]
