# Generated by Django 6.0.5 on 2026-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward', '0002_outwardentry_drone_name_outwardentry_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardentry',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='event_components',
            field=models.TextField(blank=True, null=True),
        ),
    ]
