# Generated by Django 6.0.5 on 2026-08-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('materialrequest', '0002_alter_materialrequest_status'),
        ('outward', '0003_outwardentry_moved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardentry',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineer_scrap_entries', to='materialrequest.materialrequest'),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='scrap_origin',
            field=models.CharField(choices=[('OTHER', 'Other Component'), ('MR', 'Material Request')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='outwardentry',
            index=models.Index(fields=['scrap_origin', 'material_request', 'component'], name='out_scrap_origin_mr_idx'),
        ),
    ]
