# Generated by Django 6.0.5 on 2026-07-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward', '0003_outwardentry_attendee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardentry',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=30),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outwardentry',
            name='status',
            field=models.CharField(blank=True, default='NEW', max_length=50, null=True),
        ),
    ]
