# Generated by Django 6.0.5 on 2026-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward', '0004_outwardentry_material_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardentry',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('PENDING_FINANCE', 'Pending Finance'), ('PENDING_MANAGER', 'Pending Manager'), ('FINANCE_REJECTED', 'Finance Rejected'), ('MANAGER_REJECTED', 'Manager Rejected'), ('MANAGER_APPROVED', 'Manager Approved')], default='NOT_REQUESTED', max_length=30),
        ),
    ]
