# Generated by Django 6.0.5 on 2026-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward', '0005_alter_outwardentry_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardentry',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('PENDING_MANAGEMENT', 'Pending Management'), ('MANAGEMENT_REJECTED', 'Management Rejected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=30),
        ),
    ]
