# Generated by Django 6.0.5 on 2026-06-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('received_date', models.DateField()),
                ('qc_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='PENDING', max_length=20)),
                ('qc_passed_rows', models.JSONField(blank=True, default=list)),
                ('qc_failed_rows', models.JSONField(blank=True, default=list)),
                ('qc_timestamp', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='components.component')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_entries', to='procurement.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='InwardLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inward.inwardentry')),
            ],
        ),
    ]
