# Generated by Django 6.0.5 on 2026-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardentry',
            name='qc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_INSPECTED', 'Partially Inspected'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
