# Generated by Django 6.0.5 on 2026-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardentry',
            name='qc_failed_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='qc_passed_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='qc_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
