# Generated by Django 6.0.5 on 2026-08-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0002_alter_inwardentry_qc_status'),
        ('procurement', '0002_purchaseorder_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardentry',
            name='qc_failed_action',
            field=models.CharField(choices=[('NONE', 'Action Required'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('RETURN_REQUESTED', 'Return / Refund Requested')], db_index=True, default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='replacement_purchase_order',
            field=models.ForeignKey(blank=True, help_text='Replacement PO created from this failed-QC inward entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_source_inwards', to='procurement.purchaseorder'),
        ),
    ]
