# Generated by Django 6.0.5 on 2026-08-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_number', models.CharField(max_length=100, unique=True)),
                ('bom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager'), ('APPROVED', 'Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('MODIFIED', 'Modified')], default='PENDING_MANAGER', max_length=30)),
                ('manager_rejection_reason', models.TextField(blank=True, null=True)),
                ('manager_rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('manager_approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component')),
            ],
        ),
    ]
