# Generated by Django 6.0.5 on 2026-07-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='unit_price',
        ),
    ]
