# Generated by Django 6.0.5 on 2026-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='bom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
