# Generated by Django 6.0.5 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
