# Generated by Django 6.0.5 on 2026-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_bom_bom_name_bom_project_type_bomitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='component_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unit',
            field=models.CharField(default='pc', max_length=20),
        ),
    ]
