# Generated by Django 6.0.5 on 2026-06-23 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_bomitem_component_code_bomitem_remarks_bomitem_unit'),
        ('components', '0003_component_tally_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
