# Generated by Django 6.0.5 on 2026-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('SUB_ADMIN', 'Sub Admin'), ('PROCUREMENT_MANAGER', 'Procurement Manager'), ('PROCUREMENT_EXECUTIVE', 'Procurement Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('INVENTORY_EXECUTIVE', 'Inventory Executive'), ('ENGINEERING_MANAGER', 'Engineering Manager'), ('ENGINEER', 'Engineer'), ('FINANCE_MANAGER', 'Finance Manager'), ('FINANCE_EXECUTIVE', 'Finance Executive')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
