# Generated by Django 6.0.5 on 2026-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('PROCUREMENT_MANAGER', 'Procurement Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('ENGINEERING_MANAGER', 'Engineering Manager')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
