# Generated by Django 6.0.5 on 2026-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUB_ADMIN', 'Sub Admin'), ('MANAGER', 'Manager'), ('PROCUREMENT_MANAGER', 'Procurement Manager'), ('PROCUREMENT_EXECUTIVE', 'Procurement Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('INVENTORY_EXECUTIVE', 'Inventory Executive'), ('ENGINEERING_MANAGER', 'Engineering Manager'), ('ENGINEER', 'Engineer'), ('FINANCE_MANAGER', 'Finance Manager'), ('FINANCE_EXECUTIVE', 'Finance Executive')], max_length=50, unique=True),
        ),
    ]
