# Generated by Django 6.0.5 on 2026-07-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_product_remove_vendor_product_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
