# Generated by Django 6.0.5 on 2026-09-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_city_vendor_pincode_vendor_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='payment_terms',
            new_name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_terms',
        ),
    ]
