# Generated by Django 6.0.5 on 2026-06-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='profile_image',
        ),
    ]
