# Generated by Django 6.0.5 on 2026-07-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='unit',
            field=models.CharField(blank=True, default='pcs', max_length=50),
        ),
    ]
