# Generated by Django 6.0.5 on 2026-07-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
