# Generated by Django 6.0.5 on 2026-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('component_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
