# Generated by Django 6.0.5 on 2026-08-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('componentusage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentusage',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='componentusage',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='components.component'),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='inventory_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='inventory_issue_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='inventory_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='issued_serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='item_source',
            field=models.CharField(choices=[('INVENTORY', 'In-Store Component'), ('OTHER', 'Other Item')], default='INVENTORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='component_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='component_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
