# Generated by Django 6.0.5 on 2026-06-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentusage', '0001_initial'),
    ]

    operations = [
    ]
