# Generated by Django 6.0.5 on 2026-08-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_version'),
        ('componentusage', '0002_alter_componentusage_options_and_more'),
        ('materialrequest', '0005_materialrequest_returnable_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentusage',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnable_records', to='materialrequest.materialrequest'),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='purpose',
            field=models.CharField(blank=True, choices=[('FLIGHT_TEST', 'Flight Test'), ('CUSTOMER_DEMO', 'Customer Demo'), ('QC_CHECK', 'QC Check'), ('EVENT', 'Event'), ('MISCELLANEOUS_USAGE', 'Miscellaneous Usage')], db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='return_approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING_MANAGER', 'Pending Manager'), ('PENDING_FINANCE', 'Pending Finance'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('', 'Not Checked'), ('OK', 'OK'), ('NOT_OK', 'Not OK')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='return_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentusage',
            name='return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='componentusage',
            index=models.Index(fields=['purpose', 'status'], name='cu_purpose_status_idx'),
        ),
        migrations.AddIndex(
            model_name='componentusage',
            index=models.Index(fields=['return_condition', 'return_approval_status'], name='cu_return_flow_idx'),
        ),
    ]
