# Generated by Django 6.0.5 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentusage', '0003_componentusage_material_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentusage',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='component_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
