# Generated by Django 6.0.5 on 2026-06-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('AIRFRAMES', 'Airframes'), ('COMMUNICATION', 'Communication'), ('ELECTRICALS', 'Electricals'), ('PAYLOAD', 'Payload'), ('TOOLS', 'Tools')], max_length=50)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('unit_of_measurements', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('part_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('product_link', models.URLField(blank=True, null=True)),
                ('ordering_id', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tally_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
