# Generated by Django 6.0.5 on 2026-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
