# Generated by Django 6.0.5 on 2026-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('AIRFRAMES', 'Airframes'), ('COMMUNICATION', 'Communication'), ('ELECTRICALS', 'Electricals'), ('ELECTRONICS', 'Electronics'), ('PAYLOAD', 'Payload'), ('TOOLS', 'Tools')], max_length=50),
        ),
    ]
