# Generated by Django 6.0.5 on 2026-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
