# Generated by Django 6.0.5 on 2026-06-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='tally_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
