# Generated by Django 6.0.5 on 2026-09-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
