# Generated by Django 6.0.5 on 2026-07-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_request_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('bom', models.CharField(blank=True, max_length=100, null=True)),
                ('customized_bom', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('BOM', 'BOM'), ('R&D', 'R&D')], default='BOM', max_length=10)),
                ('required_quantity', models.PositiveIntegerField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approval_status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('rejected_by', models.CharField(blank=True, help_text='Role or user who rejected', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='materialrequest.materialrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='pc', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_items', to='materialrequest.materialrequest')),
            ],
        ),
    ]
