# Generated by Django 6.0.5 on 2026-06-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('bom', models.CharField(max_length=100)),
                ('required_quantity', models.PositiveIntegerField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='materialrequest.materialrequest')),
            ],
        ),
    ]
