# Generated by Django 6.0.5 on 2026-07-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_alter_component_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_request_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('bom', models.CharField(blank=True, max_length=100, null=True)),
                ('customized_bom', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('BOM', 'BOM'), ('R&D', 'R&D')], default='BOM', max_length=10)),
                ('required_quantity', models.PositiveIntegerField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_MANAGER', 'Pending Manager'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_REJECTED', 'Admin Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('rejected_by', models.CharField(blank=True, help_text='Role or user who rejected', max_length=100, null=True)),
                ('po_raised', models.BooleanField(default=False, help_text='Marks whether procurement has raised a purchase order for this request')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pc', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('inventory_quantity', models.PositiveIntegerField(default=0)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_request_bom_items', to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='materialrequest.materialrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='pc', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_quantity', models.PositiveIntegerField(default=0)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_items', to='materialrequest.materialrequest')),
            ],
        ),
    ]
