# Generated by Django 6.0.5 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20),
        ),
    ]
