# Generated by Django 6.0.5 on 2026-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PROCUREMENT_PENDING', 'Procurement Pending'), ('INVENTORY_PENDING', 'Inventory Pending'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('PO_RAISED', 'PO Raised'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('PO_DELIVERED', 'PO Delivered'), ('QC_CHECKED', 'QC Checked'), ('PROJECT_INVENTORY_READY', 'Project Inventory Ready'), ('INVENTORY_ISSUED', 'Inventory Issued'), ('MR_COMPLETED', 'MR Completed'), ('REJECTED', 'Rejected'), ('ORDER_DELIVERED', 'Order Delivered - Legacy')], default='PENDING', max_length=30),
        ),
    ]
