# Generated by Django 6.0.5 on 2026-06-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=100)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_items', to='materialrequest.materialrequest')),
            ],
        ),
    ]
