# Generated by Django 6.0.5 on 2026-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rditem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
