# Generated by Django 6.0.5 on 2026-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_MANAGER', 'Pending Manager'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('ORDER_DELIVERED', 'Order Delivered'), ('REJECTED', 'Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=30),
        ),
    ]
