# Generated by Django 6.0.5 on 2026-06-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0002_rditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='bom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
