# Generated by Django 6.0.5 on 2026-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0002_bomitem_category_bomitem_component_bomitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='unit',
            field=models.CharField(default='pc', max_length=20),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
