# Generated by Django 6.0.5 on 2026-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0002_materialrequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='approval_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
    ]
