# Generated by Django 6.0.5 on 2026-07-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0002_materialrequest_material_request_id'),
        ('materialrequest', '0002_rditem_total_price'),
    ]

    operations = [
    ]
