# Generated by Django 6.0.5 on 2026-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0003_materialrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PROCUREMENT_PENDING', 'Procurement Pending'), ('INVENTORY_PENDING', 'Inventory Pending'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('PO_RAISED', 'PO Raised'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('PO_DELIVERED', 'PO Delivered'), ('QC_CHECKED', 'QC Checked'), ('QC_FAILED_ACTION_REQUIRED', 'QC Failed - Action Required'), ('AWAITING_REPLACEMENT_APPROVAL', 'Awaiting Replacement Approval'), ('REPLACEMENT_APPROVAL_REJECTED', 'Replacement Approval Rejected'), ('REPLACEMENT_APPROVED', 'Replacement Approved'), ('AWAITING_REPLACEMENT_DELIVERY', 'Awaiting Replacement Delivery'), ('REPLACEMENT_PARTIALLY_RECEIVED', 'Replacement Partially Received'), ('REPLACEMENT_RECEIVED', 'Replacement Received - QC Pending'), ('PROJECT_INVENTORY_READY', 'Project Inventory Ready'), ('INVENTORY_ISSUED', 'Inventory Issued'), ('MR_COMPLETED', 'MR Completed'), ('REJECTED', 'Rejected'), ('ORDER_DELIVERED', 'Order Delivered - Legacy')], default='PENDING', max_length=40),
        ),
    ]
