# Generated by Django 6.0.5 on 2026-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0003_alter_materialrequest_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='request_type',
            field=models.CharField(choices=[('BOM', 'BOM'), ('R&D', 'R&D')], default='BOM', max_length=10),
        ),
    ]
