# Generated by Django 6.0.5 on 2026-06-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0003_alter_materialrequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
