# Generated by Django 6.0.5 on 2026-07-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0003_alter_bomitem_quantity_alter_bomitem_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
