# Generated by Django 6.0.5 on 2026-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0004_bomitem_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rditem',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
