# Generated by Django 6.0.5 on 2026-08-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_version'),
        ('materialrequest', '0004_alter_materialrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='returnable_purpose',
            field=models.CharField(blank=True, choices=[('FLIGHT_TEST', 'Flight Test'), ('CUSTOMER_DEMO', 'Customer Demo'), ('QC_CHECK', 'QC Check'), ('EVENT', 'Event'), ('MISCELLANEOUS_USAGE', 'Miscellaneous Usage')], db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='project',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='request_type',
            field=models.CharField(choices=[('BOM', 'BOM'), ('R&D', 'R&D'), ('RETURNABLE', 'Returnable'), ('RETAIL_SALES', 'Retail Sales')], db_index=True, default='BOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='required_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pc', max_length=20)),
                ('inventory_quantity', models.PositiveIntegerField(default=0)),
                ('po_raised_quantity', models.PositiveIntegerField(default=0)),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('qc_passed_quantity', models.PositiveIntegerField(default=0)),
                ('qc_failed_quantity', models.PositiveIntegerField(default=0)),
                ('project_inventory_quantity', models.PositiveIntegerField(default=0)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_request_general_items', to='components.component')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='materialrequest.materialrequest')),
            ],
        ),
    ]
