# Generated by Django 6.0.5 on 2026-07-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0004_alter_materialrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=30),
        ),
    ]
