# Generated by Django 6.0.5 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0005_materialrequest_returnable_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rditem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
