# Generated by Django 6.0.5 on 2026-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0005_rditem_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='po_raised',
            field=models.BooleanField(default=False, help_text='Marks whether procurement has raised a purchase order for this request'),
        ),
    ]
