# Generated by Django 6.0.5 on 2026-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0005_materialrequest_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='customized_bom',
            field=models.BooleanField(default=False),
        ),
    ]
