# Generated by Django 6.0.5 on 2026-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0007_returnable_drone_component_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='is_hidden_from_mr_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
