# Generated by Django 6.0.5 on 2026-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialrequest', '0007_alter_materialrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_REJECTED', 'Admin Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PO_RAISED', 'PO Raised')], default='PENDING', max_length=20),
        ),
    ]
