# Generated by Django 6.0.5 on 2026-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
