# Generated by Django 6.0.5 on 2026-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='inwarded',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='received_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='shipping_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='shipping_qty',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
