# Generated by Django 6.0.5 on 2026-08-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Purchase Order'), ('REPLACEMENT', 'QC Replacement Order')], db_index=True, default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='replacement_for',
            field=models.ForeignKey(blank=True, help_text='Original standard PO that this QC replacement belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_orders', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='replacement_round',
            field=models.PositiveIntegerField(default=0, help_text='Replacement sequence number: R1, R2, R3...'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='replacement_source_inward_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='InwardEntry ID whose QC failure created this replacement order.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('REPLACEMENT_PENDING_MANAGER', 'Replacement - Pending Manager Approval'), ('REPLACEMENT_MANAGER_APPROVED', 'Replacement - Manager Approved'), ('REPLACEMENT_MANAGER_REJECTED', 'Replacement - Manager Rejected'), ('REPLACEMENT_PENDING_FINANCE', 'Replacement - Pending Finance Approval'), ('REPLACEMENT_FINANCE_APPROVED', 'Replacement - Finance Approved'), ('REPLACEMENT_FINANCE_REJECTED', 'Replacement - Finance Rejected')], default='PENDING', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('REPLACEMENT_PENDING_MANAGER', 'Replacement - Pending Manager Approval'), ('REPLACEMENT_PENDING_FINANCE', 'Replacement - Pending Finance Approval'), ('REPLACEMENT_MANAGER_REJECTED', 'Replacement - Manager Rejected'), ('REPLACEMENT_FINANCE_REJECTED', 'Replacement - Finance Rejected'), ('REPLACEMENT_APPROVED', 'Replacement Approved'), ('REPLACEMENT_ORDERED', 'Replacement Ordered'), ('REPLACEMENT_PARTIALLY_RECEIVED', 'Replacement Partially Received'), ('REPLACEMENT_RECEIVED', 'Replacement Received')], default='PENDING', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseorderapproval',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('REPLACEMENT_MANAGER_APPROVED', 'Replacement Manager Approved'), ('REPLACEMENT_MANAGER_REJECTED', 'Replacement Manager Rejected'), ('REPLACEMENT_FINANCE_APPROVED', 'Replacement Finance Approved'), ('REPLACEMENT_FINANCE_REJECTED', 'Replacement Finance Rejected'), ('REPLACEMENT_ORDERED', 'Replacement Ordered')], default='REQUESTED', max_length=40),
        ),
    ]
