# Generated by Django 6.0.5 on 2026-07-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='contact_person',
        ),
    ]
