# Generated by Django 6.0.5 on 2026-08-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
