# Generated by Django 6.0.5 on 2026-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_purchaseorder_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20),
        ),
    ]
