# Generated by Django 6.0.5 on 2026-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('PENDING_ADMIN', 'Pending Admin'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorderapproval',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_ADMIN', 'Pending Admin'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
    ]
