# Generated by Django 6.0.5 on 2026-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorderapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=20),
        ),
    ]
