# Generated by Django 6.0.5 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorderitem_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='round_off',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='freight_gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='hsn_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
