# Generated by Django 6.0.5 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorder_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_by',
            field=models.CharField(blank=True, help_text='Role or user who rejected', max_length=100, null=True),
        ),
    ]
