# Generated by Django 6.0.5 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_purchaseorder_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderapproval',
            old_name='remarks',
            new_name='finance_remarks',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='finance_remarks',
            field=models.TextField(blank=True, help_text='Finance approval/rejection remarks', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderapproval',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderapproval',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected')], default='REQUESTED', max_length=30),
        ),
    ]
