# Generated by Django 6.0.5 on 2026-09-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorder_round_off_purchaseorderitem_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderPdfVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(db_index=True, max_length=3)),
                ('financial_year', models.CharField(db_index=True, max_length=5)),
                ('sequence', models.PositiveIntegerField()),
                ('voucher_number', models.CharField(max_length=40, unique=True)),
                ('reference_po_numbers', models.JSONField(blank=True, default=list)),
                ('selected_item_ids', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(blank=True, default='', max_length=150)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('vendor_code', 'financial_year', 'sequence'), name='uniq_po_pdf_voucher_vendor_fy_seq')],
            },
        ),
    ]
