# Generated by Django 6.0.5 on 2026-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorder_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
