# Generated by Django 6.0.5 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_rename_remarks_purchaseorderapproval_finance_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
