# Generated by Django 6.0.5 on 2026-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorder_rejected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
