# Generated by Django 6.0.5 on 2026-08-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PO', 'Purchase Order'), ('MR', 'Material Request'), ('CU', 'Component Usage'), ('PROC', 'Procurement')], db_index=True, default='MR', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PROCUREMENT_PENDING', 'Procurement Pending'), ('PO_RAISED', 'PO Raised'), ('PO_DELIVERED', 'PO Delivered'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('INVENTORY_PENDING', 'Inventory Pending'), ('INVENTORY_CHECK_PENDING', 'Inventory Check Pending'), ('QC_CHECKED', 'QC Checked'), ('PROJECT_INVENTORY_READY', 'Project Inventory Ready'), ('INVENTORY_ISSUED', 'Inventory Issued'), ('MR_COMPLETED', 'MR Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=40)),
                ('receiver', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('PROCUREMENT', 'Procurement'), ('INVENTORY', 'Inventory'), ('FINANCE', 'Finance')], db_index=True, max_length=20, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['receiver', 'category', 'status'], name='notif_recv_stat_idx'), models.Index(fields=['category', 'reference_id', 'receiver'], name='notif_ref_recv_idx')],
            },
        ),
    ]
