# Generated by Django 6.0.5 on 2026-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('MR', 'Material Request'), ('CU', 'Component Usage'), ('PROC', 'Procurement'), ('SCRAP', 'Scrap'), ('BOM', 'BOM')], db_index=True, default='MR', max_length=10),
        ),
    ]
