# Generated by Django 6.0.5 on 2026-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_ADMIN', 'Pending Admin'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
