# Generated by Django 6.0.5 on 2026-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MANAGER_APPROVED', 'Manager Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
