# Generated by Django 6.0.5 on 2026-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reference_module',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('MR', 'Material Request'), ('CU', 'Component Usage')], default='MR', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
