# Generated by Django 6.0.5 on 2026-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='requested_by',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
