# Generated by Django 6.0.5 on 2026-07-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('MR', 'Material Request'), ('CU', 'Component Usage'), ('PROC', 'Procurement')], default='MR', max_length=10),
        ),
    ]
