# Generated by Django 6.0.5 on 2026-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_recipient_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_cat_stat_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('MR', 'Material Request'), ('CU', 'Component Usage'), ('PROC', 'Procurement'), ('SCRAP', 'Scrap'), ('BOM', 'BOM'), ('SALES', 'Sales')], db_index=True, default='MR', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('PROCUREMENT', 'Procurement'), ('INVENTORY', 'Inventory'), ('FINANCE', 'Finance'), ('MANAGEMENT', 'Management')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_MANAGEMENT', 'Pending Management'), ('MANAGEMENT_APPROVED', 'Management Approved'), ('MANAGEMENT_REJECTED', 'Management Rejected'), ('PROCUREMENT_PENDING', 'Procurement Pending'), ('PO_RAISED', 'PO Raised'), ('PO_DELIVERED', 'PO Delivered'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('INVENTORY_PENDING', 'Inventory Pending'), ('INVENTORY_CHECK_PENDING', 'Inventory Check Pending'), ('QC_CHECKED', 'QC Checked'), ('PROJECT_INVENTORY_READY', 'Project Inventory Ready'), ('INVENTORY_ISSUED', 'Inventory Issued'), ('MR_COMPLETED', 'MR Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=40),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient_user',
        ),
    ]
