# Generated by Django 6.0.5 on 2026-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('PROCUREMENT', 'Procurement'), ('MANAGER', 'Manager')], max_length=20, null=True),
        ),
    ]
