# Generated by Django 6.0.5 on 2026-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
