# Generated by Django 6.0.5 on 2026-07-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('PENDING_FINANCE', 'Pending Finance'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
