# Generated by Django 6.0.5 on 2026-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('INVENTORY', 'Inventory'), ('PROCUREMENT', 'Procurement'), ('FINANCE', 'Finance')], max_length=20, null=True),
        ),
    ]
